### ISSUE TITLE
Link naar styleguide

### ISSUE THREAD

**Issue by Saif8599** [FatimaZelay/look-and-feel-corporate-identity#23]
Link in de html naar de externe stylesheet ipv eigen project

**Comment by EBok1** [comment]
Als je linkt naar je gezamenlijke stylesheet in je `<head>` hoef je het bestand 'qatarmuseums.css' niet in je code te zetten. 
Bovenaan je algemene styleguide staat de link die je kunt gebruiken. Pas deze aan en zet hem in je code.
